version: '3'
services:
  kaddem:
    image: 5ds1_g7_kaddem:tagname
    restart: on-failure
    ports:
      - '8089:8089'
    depends_on:
      - mysql
 
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ismail
      MYSQL_DATABASE: projDevOps
      MYSQL_USER: root
      MYSQL_PASSWORD:
