version: "3"
services:
  spring-tpachatproject:
    image: ahmedelamri/5ds1_g7_kaddem
    ports:
      - "8089:8089"
    networks:
      - kaddem
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/projDevOps
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    volumes:
      -  /home/mysql/ahmeddata:/var/lib/mysql:rw
    networks:
      - kaddem
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=projDevOps

networks:
  kaddem: